In [35]:
import pandas as pd

df = pd.read_csv('online_vs_offline_learning_dataset.csv')
df

,Learning_Mode,Subject,Study_Hours,Retention_Score,Focus_Level,Exam_Score
0,Offline,English,7.7,51,96,70
1,Offline,English,6.2,90,82,81
2,Online,English,1.2,75,66,71
3,Online,Math,6.5,80,64,77
4,Online,English,5.5,95,58,78
...,...,...,...,...,...,...
995,Online,Math,7.5,57,81,61
996,Offline,History,7.8,93,79,88
997,Online,Math,5.4,55,63,55
998,Offline,English,2.3,68,59,59
999,Online,English,4.7,69,51,58

In [36]:
print(df.to_string())

    Learning_Mode      Subject  Study_Hours  Retention_Score  Focus_Level  Exam_Score
0         Offline      English          7.7               51           96          70
1         Offline      English          6.2               90           82          81
2          Online      English          1.2               75           66          71
3          Online         Math          6.5               80           64          77
4          Online      English          5.5               95           58          78
5         Offline      Science          4.7               75           40          59
6         Offline  Programming          6.1               61           68          67
7          Online         Math          1.8               57           72          62
8         Offline      History          2.4               94           44          72
9         Offline      History          2.1               63           59          57
10        Offline      History          7.0               53           99          76
11        Offline  Programming          6.3               97           68          86
12         Online      English          1.3               87           76          78
13        Offline         Math          3.7               90           61          83
14         Online      Science          4.4               64           53          54
15         Online         Math          1.7               64           56          60
16         Online      Science          7.1               48           49          47
17         Online      History          2.3               45           51          52
18         Online      History          1.5               40           70          56
19        Offline  Programming          6.5               65           89          73
20         Online      History          7.7              100           41          80
21        Offline      English          1.6               50           48          49
22        Offline      Science          5.2               74           48          60
23        Offline         Math          3.2               64           54          60
24         Online         Math          1.9              100           51          79
25        Offline      History          4.7               57           99          76
26         Online  Programming          5.4               93           72          88
27         Online      History          2.5               84           97          85
28        Offline      Science          6.9               42           66          47
29        Offline      Science          1.5               97           70          85
30         Online      Science          1.6               80           59          70
31         Online  Programming          6.2               93           83          86
32        Offline      English          2.6               46           84          60
33        Offline      English          5.7              100          100          99
34        Offline         Math          2.7               99           49          81
35        Offline      English          4.4               44           42          46
36         Online         Math          6.0               44           85          65
37        Offline      Science          2.2               79           69          74
38         Online      History          6.6               71           84          72
39        Offline         Math          7.1               62           51          61
40        Offline  Programming          3.7               80           77          80
41         Online      Science          7.5               99           46          73
42         Online      English          5.2              100           49          84
43         Online      Science          4.2               40           79          60
44        Offline         Math          7.7               72           80          75
45         Online      Science          6.1               55           65          60
46         Online      English          2.3               49           84          67
47        Offline      Science          5.1               79           98          91
48         Online         Math          7.1               59           77          68
49        Offline      History          4.7               73           68          73
50         Online      History          4.5               98           91          94
51        Offline      English          4.8               59           87          75
52         Online      English          2.3               41           73          49
53         Online         Math          2.6               94           44          76
54         Online         Math          5.2               90           96          89
55         Online      English          7.4               72           91          75
56         Online      History          2.5               96           41          79
57         Online      English          3.1               60           86          68
58        Offline         Math          1.3               54           91          63
59         Online      History          7.8               81           90          82
60        Offline      History          6.8               62           89          71
61         Online         Math          2.1               47           99          66
62        Offline      English          7.0               70           62          65
63         Online      History          4.9               51           61          55
64        Offline  Programming          7.0               82           68          81
65         Online      English          1.2               58           62          61
66         Online      Science          3.3               98           50          76
67        Offline      English          7.0               92           82          83
68        Offline  Programming          7.3              100           83          95
69         Online      History          7.9               46           88          66
70        Offline      Science          2.0               62          100          72
71         Online      English          1.9               62           80          67
72         Online         Math          3.6               64           40          57
73        Offline         Math          4.8               55           99          68
74         Online      Science          6.3               54           44          45
75        Offline      History          7.4               77           50          65
76        Offline      English          1.9               74           81          76
77         Online         Math          1.5               98           58          77
78        Offline  Programming          3.2               90           58          79
79         Online      English          7.4               94           58          74
80         Online  Programming          4.1               87           66          83
81        Offline      History          3.4               84           92          90
82        Offline  Programming          3.5               82          100          91
83        Offline  Programming          5.1               73           42          59
84        Offline  Programming          5.7               88           98          88
85        Offline  Programming          4.9              100           93          96
86         Online      English          5.2               62           53          58
87         Online      Science          4.2               54           95          68
88         Online      Science          6.8               83           46          72
89         Online  Programming          4.4               68           87          76
90        Offline  Programming          3.2               53           63          56
91         Online      English          1.8               67           60          63
92        Offline      English          7.8               65           96          77
93        Offline      English          3.1               51           87          64
94         Online      English          5.5               91           90          93
95         Online  Programming          5.6               73           54          69
96        Offline         Math          7.5               50           79          66
97         Online      English          6.2               95           79          89
98        Offline         Math          5.1               63           69          63
99         Online      Science          2.2               78           69          77
100       Offline      English          1.5               79          100          89
101        Online      Science          4.5               99           67          83
102        Online      Science          4.3               61           81          66
103       Offline      English          4.4               54           84          66
104        Online      History          3.1               42           96          64
105        Online  Programming          7.7               45          100          65
106       Offline      History          4.1               68           50          63
107        Online      Science          1.8               79           43          59
108       Offline      Science          6.0               84           53          72
109       Offline      Science          5.9               81           59          69
110       Offline      Science          1.9               57           89          67
111       Offline         Math          3.7               49           43          51
112       Offline      History          1.6              100           67          82
113        Online      English          5.8               85           71          74
114        Online  Programming          7.4               47           70          52
115        Online      English          1.6               81           85          84
116       Offline      English          1.1               98           68          85
117       Offline  Programming          6.1               53           41          46
118       Offline         Math          4.6               92           94          94
119       Offline      Science          6.5               59           83          72
120       Offline      English          2.1               90           89          86
121        Online  Programming          6.3               99           45          75
122        Online      Science          5.7              100           90          99
123       Offline      History          1.5               76           60          74
124        Online      Science          5.6               48           51          45
125        Online      History          1.6               87           70          85
126        Online  Programming          2.7               62           82          65
127        Online      History          4.9               77           92          87
128        Online      English          1.5               49           72          53
129       Offline      English          7.0               72           95          76
130        Online      English          7.6               41           82          53
131       Offline      History          1.8               57           96          77
132       Offline      English          2.7               46           98          69
133       Offline      Science          2.8               74           94          82
134        Online      History          6.0               56           83          67
135        Online      History          4.8               48           63          57
136        Online      English          1.6               51           71          61
137        Online  Programming          4.8               70           76          72
138        Online      Science          3.2               55           56          52
139       Offline      History          6.8              100           58          78
140       Offline      History          6.2              100           78          89
141       Offline      History          3.4               57          100          72
142        Online         Math          1.3               75           44          66
143        Online      History          7.8               97           70          89
144        Online         Math          4.1               56           79          61
145       Offline         Math          4.8               83           73          82
146       Offline         Math          4.7               64           83          70
147       Offline         Math          5.8               77           75          73
148       Offline      English          3.2              100           84          91
149       Offline      English          6.2              100           69          92
150       Offline      English          4.1              100           98          99
151        Online      Science          2.0               89           82          86
152        Online      English          7.2               50          100          75
153       Offline         Math          5.3               87           63          74
154        Online         Math          7.2               43           82          61
155        Online      English          5.0               77           99          87
156        Online      History          7.7               62           79          70
157       Offline      History          4.1               61           80          70
158        Online      Science          3.7               91           46          74
159       Offline  Programming          1.7              100           73          89
160        Online      History          3.8               50           97          63
161        Online      History          2.9               91           53          70
162       Offline         Math          7.0               95          100         100
163        Online      History          1.0               82           65          80
164       Offline      Science          3.5               71           47          60
165        Online      English          3.2               41           61          51
166       Offline      History          5.1               86          100          92
167        Online      English          3.5               79           81          76
168       Offline         Math          1.4              100           74          87
169       Offline         Math          5.9               68           59          59
170       Offline      History          1.8               71           91          79
171       Offline      Science          1.8               57           86          71
172       Offline  Programming          2.1               47           53          44
173        Online         Math          1.4               45           98          71
174        Online         Math          3.4               83           90          82
175       Offline  Programming          6.7               57           68          58
176       Offline      Science          2.0               78           79          76
177       Offline      English          3.8              100           85          97
178       Offline      History          6.3               91           78          82
179       Offline      Science          5.2               86           98          91
180        Online  Programming          2.8               54           71          55
181       Offline  Programming          1.1              100           89          92
182        Online         Math          3.1               43           96          59
183        Online         Math          4.2               77           96          80
184       Offline      English          3.1               66           55          61
185        Online      English          3.7               70           97          80
186        Online      History          5.0               61           80          67
187       Offline  Programming          3.3               62           65          66
188        Online      English          3.3               50           95          66
189       Offline      Science          7.0               73           83          80
190        Online      English          4.8               63           48          58
191       Offline  Programming          5.5               65           53          58
192       Offline      English          5.6              100           66          84
193       Offline      History          7.6               95           64          78
194        Online      English          1.4               40           69          49
195        Online      English          6.6               70           49          66
196       Offline         Math          7.0               60           88          73
197       Offline  Programming          5.0              100           50          76
198       Offline         Math          4.4               57           81          65
199       Offline      Science          3.1               99           72          84
200        Online      History          2.2               40           75          58
201        Online      English          4.7               74           63          66
202        Online      English          5.2               59           56          55
203        Online      History          4.8               47           64          52
204        Online         Math          7.1               93           95          95
205        Online      History          6.3               54           85          61
206        Online  Programming          1.8               91           60          75
207        Online      History          6.3               82           65          80
208        Online      History          5.8               69           52          59
209       Offline  Programming          6.8               59           60          58
210       Offline  Programming          4.9               80           49          68
211       Offline      English          5.9               67           92          80
212       Offline      Science          3.3               87           48          68
213        Online      Science          4.1              100           86          99
214        Online  Programming          7.4               66           55          64
215        Online  Programming          2.3               43           73          55
216        Online  Programming          2.3               50           97          73
217       Offline         Math          7.3               58           51          51
218       Offline         Math          7.5               90           91          90
219        Online         Math          1.0               58           89          67
220       Offline         Math          6.7               64           80          74
221       Offline      English          6.0               96           44          77
222        Online      History          7.8               43           95          65
223        Online      History          3.3               59           45          57
224        Online      History          6.6               98           78          92
225        Online  Programming          2.8               60           98          77
226       Offline      History          6.9               54           68          58
227        Online  Programming          2.0               75           68          76
228       Offline         Math          3.6               97           53          77
229        Online  Programming          3.0               68           63          71
230        Online         Math          6.7               88           82          81

In [37]:
df.head()

,Learning_Mode,Subject,Study_Hours,Retention_Score,Focus_Level,Exam_Score
0,Offline,English,7.7,51,96,70
1,Offline,English,6.2,90,82,81
2,Online,English,1.2,75,66,71
3,Online,Math,6.5,80,64,77
4,Online,English,5.5,95,58,78

In [38]:
df.head(20)

,Learning_Mode,Subject,Study_Hours,Retention_Score,Focus_Level,Exam_Score
0,Offline,English,7.7,51,96,70
1,Offline,English,6.2,90,82,81
2,Online,English,1.2,75,66,71
3,Online,Math,6.5,80,64,77
4,Online,English,5.5,95,58,78
5,Offline,Science,4.7,75,40,59
6,Offline,Programming,6.1,61,68,67
7,Online,Math,1.8,57,72,62
8,Offline,History,2.4,94,44,72
9,Offline,History,2.1,63,59,57
10,Offline,History,7.0,53,99,76
11,Offline,Programming,6.3,97,68,86
12,Online,English,1.3,87,76,78
13,Offline,Math,3.7,90,61,83
14,Online,Science,4.4,64,53,54
15,Online,Math,1.7,64,56,60
16,Online,Science,7.1,48,49,47
17,Online,History,2.3,45,51,52
18,Online,History,1.5,40,70,56
19,Offline,Programming,6.5,65,89,73

In [39]:
df.tail()

,Learning_Mode,Subject,Study_Hours,Retention_Score,Focus_Level,Exam_Score
995,Online,Math,7.5,57,81,61
996,Offline,History,7.8,93,79,88
997,Online,Math,5.4,55,63,55
998,Offline,English,2.3,68,59,59
999,Online,English,4.7,69,51,58

In [40]:
df.tail(7)

,Learning_Mode,Subject,Study_Hours,Retention_Score,Focus_Level,Exam_Score
993,Online,History,3.2,44,46,41
994,Online,History,1.6,79,77,76
995,Online,Math,7.5,57,81,61
996,Offline,History,7.8,93,79,88
997,Online,Math,5.4,55,63,55
998,Offline,English,2.3,68,59,59
999,Online,English,4.7,69,51,58

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Learning_Mode    1000 non-null   str
 1   Subject          1000 non-null   str
 2   Study_Hours      1000 non-null   float64
 3   Retention_Score  1000 non-null   int64
 4   Focus_Level      1000 non-null   int64
 5   Exam_Score       1000 non-null   int64
dtypes: float64(1), int64(3), str(2)
memory usage: 47.0 KB

In [42]:
df.describe()

       Study_Hours  Retention_Score  Focus_Level   Exam_Score
count  1000.000000       1000.00000  1000.000000  1000.000000
mean      4.563500         72.69100    71.261000    71.675000
std       2.000115         17.69827    18.053166    12.984297
min       1.000000         40.00000    40.000000    39.000000
25%       2.800000         58.00000    56.000000    62.000000
50%       4.700000         72.00000    72.000000    72.000000
75%       6.300000         88.00000    87.000000    81.000000
max       8.000000        100.00000   100.000000   100.000000

In [43]:
df.shape

(1000, 6)

In [44]:
df.size

6000

In [45]:
df.columns

Index(['Learning_Mode', 'Subject', 'Study_Hours', 'Retention_Score',
       'Focus_Level', 'Exam_Score'],
      dtype='str')

In [46]:
df.groupby('Learning_Mode')['Exam_Score'].mean()

Learning_Mode
Offline    73.136
Online     70.214
Name: Exam_Score, dtype: float64

In [47]:
df.groupby('Subject')['Exam_Score'].mean()

Subject
English        74.271429
History        71.575758
Math           70.092308
Programming    71.230769
Science        71.041860
Name: Exam_Score, dtype: float64

In [48]:
df.groupby('Learning_Mode').count()

               Subject  Study_Hours  Retention_Score  Focus_Level  Exam_Score
Learning_Mode
Offline            500          500              500          500         500
Online             500          500              500          500         500

In [49]:
import numpy as np
df['Score Category'] = np.where(df['Exam_Score'] > 50 , "Pass", "Fail")
df

,Learning_Mode,Subject,Study_Hours,Retention_Score,Focus_Level,Exam_Score,Score Category
0,Offline,English,7.7,51,96,70,Pass
1,Offline,English,6.2,90,82,81,Pass
2,Online,English,1.2,75,66,71,Pass
3,Online,Math,6.5,80,64,77,Pass
4,Online,English,5.5,95,58,78,Pass
...,...,...,...,...,...,...,...
995,Online,Math,7.5,57,81,61,Pass
996,Offline,History,7.8,93,79,88,Pass
997,Online,Math,5.4,55,63,55,Pass
998,Offline,English,2.3,68,59,59,Pass
999,Online,English,4.7,69,51,58,Pass

In [50]:
data = {
    'eid' : [1,2,3,4],
    'name' : ['A','B','C','D'],
    'salary' : [30000,40000,50000,60000]
}

df = pd.DataFrame(data)
df

   eid name  salary
0    1    A   30000
1    2    B   40000
2    3    C   50000
3    4    D   60000

In [51]:
df['Annual_salary'] = df['salary'] * 12
df

   eid name  salary  Annual_salary
0    1    A   30000         360000
1    2    B   40000         480000
2    3    C   50000         600000
3    4    D   60000         720000

In [58]:
df = ['basic salary'] = df['salary'] - 1000
df

SyntaxError: cannot assign to literal (520802352.py, line 1)

# merge

In [52]:
emp = {
    'id' : [1,2,3,4,5],
    'name' : ['A','B','C','D','E']   
}
df1 = pd.DataFrame(emp)
df1

emp_info = {
    'id' : [1,2,3,4,6],
    'department' : ['IT', 'IT', 'Sales', 'Sales', 'Finance']
}
df2 = pd.DataFrame(emp_info)
df2

   id department
0   1         IT
1   2         IT
2   3      Sales
3   4      Sales
4   6    Finance

In [53]:
emp_information = pd.merge(df1,df2, on='id')

In [54]:
emp_information

   id name department
0   1    A         IT
1   2    B         IT
2   3    C      Sales
3   4    D      Sales

In [55]:
left = pd.merge(df1,df2, how='left')
left

   id name department
0   1    A         IT
1   2    B         IT
2   3    C      Sales
3   4    D      Sales
4   5    E        NaN

In [56]:
right = pd.merge(df1,df2, how='right')
right

   id name department
0   1    A         IT
1   2    B         IT
2   3    C      Sales
3   4    D      Sales
4   6  NaN    Finance

In [57]:
outer = pd.merge(df1,df2, how='outer')
outer

   id name department
0   1    A         IT
1   2    B         IT
2   3    C      Sales
3   4    D      Sales
4   5    E        NaN
5   6  NaN    Finance